---
version: '3'

services:
    mysql:
      hostname: mysql
      image: "mysql/mysql-server:5.7.30"
      container_name: mysql
      restart: always
      ports:
        - "3306:3306"
      volumes:
        - "${MYSQL_DIR}/config/my.cnf:/etc/my.cnf"
        - "${MYSQL_DIR}/data:/var/lib/mysql"
        - "${MYSQL_DIR}/init:/docker-entrypoint-initdb.d"
      # links:
      #   - manager
      #   - gateway
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
        TZ: ${TIME_ZONE}
      logging:
        driver: "json-file"
        options:
          max-size: "1000k"
          max-file: "20"
      networks:
        - fizz-gateway


    redis:
      hostname: redis
      image: "redis:6.0.8"
      container_name: redis
      restart: always
      ports: 
        - "6379:6379"
      volumes:
        - "${REDIS_DIR}/config/redis.conf:/usr/local/etc/redis/redis.conf"
        - "${REDIS_DIR}/data:/data"
      # links:
      #   - manager
      #   - gateway
      environment: 
        TZ: ${TIME_ZONE}
      command:
        /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
      logging:
        driver: "json-file"
        options:
          max-size: "1000k"
          max-file: "20"
      networks:
        - fizz-gateway  
       
    manager:
      depends_on:
        - mysql
        - redis
      image: "fizzgate/fizz-manager-professional:2.0.0"
      volumes:
        - "${MANAGER_DIR}/config/application-prod.yml:/opt/fizz-manager-professional/application-prod.yml"
        - "${MANAGER_DIR}/logs:/opt/fizz-manager-professional/logs"
      ports:
        - "8000:8000"
      restart: always
      environment:
        - "spring.redis.host=redis"
        - "spring.redis.port=6379"
        - "spring.redis.password=${REDIS_PASS}"
        - "spring.redis.database=9"
        - "spring.datasource.url=jdbc:mysql://mysql:3306/fizz_manager?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true"
        - "spring.datasource.username=root"
        - "spring.datasource.password=${MYSQL_ROOT_PASSWORD}"
      networks:
        - fizz-gateway  
    
    gateway: 
      depends_on:
        - redis
        - mysql
      image: "fizzgate/fizz-gateway-community:2.0.0"
      volumes:
        - "${GATEWAY_DIR}/config/application.yml:/opt/fizz-gateway-community/application.yml"
        - "${GATEWAY_DIR}/logs:/opt/fizz-gateway-community/logs"
      ports:
        - "8600:8600"
      restart: always
      environment:
        - "aggregate.redis.host=redis"
        - "aggregate.redis.port=6379"
        - "aggregate.redis.password=${REDIS_PASS}"
        - "aggregate.redis.database=10"
      networks:
        - fizz-gateway  

networks:
  fizz-gateway:
    driver: bridge
